project:
  name: "p100o9"
  version: "raw"
  run_id: "${project.name}_${project.version}_${model.type}"
  output_dir: "results/${project.run_id}"

data:
  data_root: "F:/XRR_AI/data"
  data_file: "${data.data_root}/p100o9_raw.h5"

training:
  batch_size: 256
  epochs: 200
  learning_rate: 0.001
  seed: 42
  patience: 50

model:
  type: "hybrid"
