project:
  name: "p100o9"
  type: "raw"
  run_id: "${project.name}_${project.type}_${model.name}"
  output_dir: "results/${project.run_id}"

data:
  data_dir: "X:/XRR_AI/hdf5_XRR/data"
  input_file: "${data.data_dir}/p100o9_raw.h5"

training:
  batch_size: 256
  epochs: 200
  learning_rate: 0.001
  seed: 42
  patience: 50

model:
  name: "hybrid"
