project:
  name: "p300o6"
  version: "raw"
  run_id: "${project.name}_${project.version}_${training.type}"

path:
  log_dir: ./logs
  data_root: "D:\\03_Resources\\Experiment\\Data\\XRR_AI\\data"
  # data_root: "X:\\XRR_AI\\hdf5_XRR\\data"
  data_file: "${path.data_root}/${project.name}_${project.version}.h5"
  output_dir: "./results"

training:
  batch_size: 256
  epochs: 200
  learning_rate: 0.001
  seed: 42
  patience: 50
  type: "hybrid"
